---
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - master
  - name: develop
    channel: beta
    prerelease: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - assets:
      - /tmp/workspace/build/package/splunkbase/*
      - /tmp/workspace/build/package/deployment/*