---
branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - master
  - name: develop
    channel: beta
    prerelease: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
      - /home/circleci/project/build/package/splunkbase/*.{tar.gz}
      - /home/circleci/project/build/package/deployment/*.{tar.gz, json}