#Splunk Connect for Syslog (SC4S) by Splunk, Inc.
#
#To the extent possible under law, the person who associated CC0 with
#Splunk Connect for Syslog (SC4S) has waived all copyright and related or neighboring rights
#to Splunk Connect for Syslog (SC4S).
#
#You should have received a copy of the CC0 legalcode along with this
#work.  If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
ARG SPLUNK_IP
FROM circleci/python:3.7-browsers
ARG SPLUNK_IP
USER circleci
RUN mkdir -p /home/circleci/work/tests
RUN mkdir -p /home/circleci/work/test-results/functional

