name: Run Tests

on:
  pull_request:
    branches:
      - "**"
  label:
    types:
      - created

jobs:
  build:
    if: ${{ github.event.label.name == 'preserve_infra' }}
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: |
        echo "running test"
        sleep 300
        echo "End"