name: Run Tests

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    if: ${{ github.event.label.name == 'preserve_infra' }}
    runs-on: ubuntu-latest
    steps:
    - name: Run tests
      run: echo running tests