name: test-workflow
on: 
  workflow_dispatch:
    inputs:
      TRIGGER_ALL_PIPELINE:
        description: 'TRIGGER_ALL_PIPELINE'
        default: false
        type: boolean
      JOB_LIST:
        description: "JOB_LIST: NOAH_CO2_canary, NOAH_CO2_batch2, NOAH_CO2_batch3, NOAH_CO2_batch4, NOAH_CO2_batch5, STANDALONE_BATCH1, STANDALONE_BATCH2. \nNOTE: This parameter is only applicable for \"Trigger ALL\""
        default: 'NOAH_CO2_canary'
      STACK_TYPE:
        description: 'STACK_TYPE'
        default: 'Noah_SHC'
      SPLUNK_VERSION:
        description: 'SPLUNK_VERSION'
        default: '8.2.2107'
      TEST_TYPE:
        description: 'Tests you want to execute, Must match foldername in test directory i.e knowledge, ui, modinput_functional. NOTE: This parameter is only applicable for "Individual Addon Tests" and not for "Trigger ALL".'
        default: 'knowledge'
      BROWSER:
        description: 'Browser to execute UI tests on, e.g. chrome, firefox, safari. If require then pass the browser_version like, chrome:98. NOTE: This parameter is only applicable for "Individual Addon Tests" and not for "Trigger ALL".'
        default: 'chrome'
      CHECKOUT_CODE:
        description: 'Checkout specific Tag/Branch/Commit i.e v4.2.2, main, 86a3d27ef28181434c8b073a82bda3041787dc38. NOTE: This parameter is only applicable for "Individual Addon Tests" and not for "Trigger ALL".'
        default: 'latest_splunkbase_version'
      ADDITIONAL_FILTER:
        description: 'Additional filter for pytest command, e.g. -k test_splunk_internal_errors, -m splunk_searchtime_fields. NOTE: This parameter is only applicable for "Individual Addon Tests" and not for "Trigger ALL".'
      CREATE_INDEXES:
        description: 'Provide False if the required indexes for SC4S are already created in stack from previous executions. NOTE: This parameter is only applicable for "Individual Addon Tests" and not for "Trigger ALL".'
        default: true
        required: false
        type: boolean
      DELETE_STACK:
        description: 'Provide False to preserve the Noah stack created while execution. NOTE: This parameter is only applicable for "Individual Addon Tests" and not for "Trigger ALL".'
        default: true
        required: false
        type: boolean
      
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "TRIGGER_ALL_PIPELINE: $TRIGGER_ALL_PIPELINE"
          echo "JOB_LIST: $JOB_LIST"
          echo "STACK_TYPE: $STACK_TYPE"
          echo "SPLUNK_VERSION: $SPLUNK_VERSION"
          echo "TEST_TYPE: $TEST_TYPE"
          echo "BROWSER: $BROWSER"
          echo "CHECKOUT_CODE: $CHECKOUT_CODE"
          echo "ADDITIONAL_FILTER: $ADDITIONAL_FILTER"
          echo "CREATE_INDEXES: $CREATE_INDEXES"
          echo "DELETE_STACK: $DELETE_STACK"
          echo "EVENT_TYPE: $EVENT_TYPE"
        env:
          TRIGGER_ALL_PIPELINE: ${{ inputs.TRIGGER_ALL_PIPELINE }}
          STACK_TYPE: ${{ inputs.STACK_TYPE }}
          SPLUNK_VERSION: ${{ inputs.SPLUNK_VERSION }}
          JOB_LIST: ${{ inputs.JOB_LIST }}
          TEST_TYPE: ${{ inputs.TEST_TYPE }}
          BROWSER: ${{ inputs.BROWSER }}
          CHECKOUT_CODE: ${{ inputs.CHECKOUT_CODE }}
          ADDITIONAL_FILTER: ${{ inputs.ADDITIONAL_FILTER }}
          CREATE_INDEXES: ${{ inputs.CREATE_INDEXES }}
          DELETE_STACK: ${{ inputs.DELETE_STACK }}
          EVENT_TYPE: ${{ github.event_name }}
          
  # call-workflow:
  #   uses: splunk/addonfactory-workflow-addon-release/.github/workflows/reusable-build-test-release.yml@v1.7
  #   secrets:
  #     GH_TOKEN_ADMIN: ${{ secrets.GH_TOKEN_ADMIN }}
  #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     SEMGREP_PUBLISH_TOKEN: ${{ secrets.SEMGREP_PUBLISH_TOKEN }}
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     VT_API_KEY: ${{ secrets.VT_API_KEY }}
  #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  #     OTHER_TA_REQUIRED_CONFIGS: ${{ secrets.OTHER_TA_REQUIRED_CONFIGS }}
  #     FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
