name: test-workflow
on: 
  workflow_dispatch:
    inputs:
      SPLUNK_VERSION:
        default: '8.2.2107'
        description: 'SPLUNK_VERSION'
      TEST_TYPE:
        description: 'Tests you want to execute, Must match foldername in test directory i.e knowledge, ui, modinput_functional.'
        default: 'knowledge'
      BROWSER:
        description: 'Browser to execute UI tests on, e.g. chrome, firefox, safari.\nIf require then pass the browser_version like, chrome:98.'
        default: 'chrome'
      SC4S_VERSION:
        description: 'SC4S version that should be used for addon test-executions, e.g. 1.95.0'
        default: 'latest'
      SC4S_REGISTRY:
        description: "SC4S registry that should be used for installing the above SC4S version from,\ne.g. ghcr.io/splunk/splunk-connect-for-syslog/container2 for SC4S Version 2.X\n ghcr.io/splunk/splunk-connect-for-syslog/container for SC4S Version 1.X."
        default: 'ghcr.io/splunk/splunk-connect-for-syslog/container2'
      ADDITIONAL_FILTER:
        description: 'Additional filter for pytest command, e.g. -k test_splunk_internal_errors'
      PYTEST_EXPECT_FILE:
        default: '.pytest.expect'
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "SPLUNK_VERSION: $SPLUNK_VERSION"
          echo "TEST_TYPE: $TEST_TYPE"
          echo "BROWSER: $BROWSER"
          echo "SC4S_VERSION: $SC4S_VERSION"
          echo "SC4S_REGISTRY: $SC4S_REGISTRY"
          echo "ADDITIONAL_FILTER: $ADDITIONAL_FILTER"
          echo "PYTEST_EXPECT_FILE: $PYTEST_EXPECT_FILE"
          echo "EVENT_TYPE: $EVENT_TYPE"
        env:
          SPLUNK_VERSION: ${{ inputs.SPLUNK_VERSION }}
          TEST_TYPE: ${{ inputs.TEST_TYPE }}
          BROWSER: ${{ inputs.BROWSER }}
          SC4S_VERSION: ${{ inputs.SC4S_VERSION }}
          SC4S_REGISTRY: ${{ inputs.SC4S_REGISTRY }}
          ADDITIONAL_FILTER: ${{ inputs.ADDITIONAL_FILTER }}
          PYTEST_EXPECT_FILE: ${{ inputs.PYTEST_EXPECT_FILE }}
          EVENT_TYPE: ${{ github.event_name }}
          
  # call-workflow:
  #   uses: splunk/addonfactory-workflow-addon-release/.github/workflows/reusable-build-test-release.yml@v1.7
  #   secrets:
  #     GH_TOKEN_ADMIN: ${{ secrets.GH_TOKEN_ADMIN }}
  #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     SEMGREP_PUBLISH_TOKEN: ${{ secrets.SEMGREP_PUBLISH_TOKEN }}
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #     VT_API_KEY: ${{ secrets.VT_API_KEY }}
  #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  #     OTHER_TA_REQUIRED_CONFIGS: ${{ secrets.OTHER_TA_REQUIRED_CONFIGS }}
  #     FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
