on:
  pull_request: {}
  push:
    branches:
    - main
    - test/semgrep-dashboard
name: Semgrep
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: returntocorp/semgrep-action@v1
      with:
        auditOn: push
        publishToken: 780ae019b720f69cec1b99e05d88f1dfb09c7b6346e977ccbf50735c6500c26c
        publishDeployment: 342
        config: p/ci
      env:
        GITHUB_TOKEN: ${{ secrets.semgrep_test }}
