name: Snyk testing

on: [push]
  # pull_request:
  #   branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
      - uses: snyk/actions/setup@master
      - name: snyk auth - authenticate snyk use environment variables to add token
        run:  snyk auth e1086d1f-def2-4c81-bcf2-2d6002c14c05
      - name: snyk test requirements_dev.txt 
        if: always()
        run: |
            if [ -f "requirements_dev.txt" ] && [[ $(wc -l <requirements_dev.txt) -ge 6 ]]; then
              python3.7 -m virtualenv ~/.venv -p python3 >/dev/null 2>&1
              source ~/.venv/bin/activate >/dev/null 2>&1
              (pip install -q -r requirements_dev.txt --use-deprecated=legacy-resolver || true) >/dev/null 2>&1
              snyk test --severity-threshold=low --print-deps --file=requirements_dev.txt --package-manager=pip --command=python3 --json-file-output=snyk-scan-requirements_dev.json --sarif-file-snyk-scan-requirements_dev.sarif
              deactivate
              rm -rf ~/.venv
            fi
      - name: snyk test requirements_py2_dev.txt
        if: always()
        run: |
            if [ -f "requirements_dev.txt" ] && [[ $(wc -l <requirements_dev.txt) -ge 6 ]]; then
              python3.7 -m virtualenv ~/.venv -p python3 >/dev/null 2>&1
              source ~/.venv/bin/activate >/dev/null 2>&1
              (pip install -q -r requirements_py2_dev.txt --use-deprecated=legacy-resolver || true) >/dev/null 2>&1
              snyk test --severity-threshold=low --print-deps --file=requirements_py2_dev.txt --package-manager=pip --command=python3 --json-file-output=snyk-scan-requirements_dev.json --sarif-file-snyk-scan-requirements_dev.sarif
              deactivate
              rm -rf ~/.venv
            fi
      - name: snyk test requirements_addon_specific.txt
        if: always()
        run: |
            if [ -f "requirements_dev.txt" ] && [[ $(wc -l <requirements_dev.txt) -ge 6 ]]; then
              python3.7 -m virtualenv ~/.venv -p python3 >/dev/null 2>&1
              source ~/.venv/bin/activate >/dev/null 2>&1
              (pip install -q -r requirements_addon_specific.txt --use-deprecated=legacy-resolver || true) >/dev/null 2>&1
              snyk test --severity-threshold=low --print-deps --file=requirements_addon_specific.txt --package-manager=pip --command=python3 --json-file-output=snyk-scan-requirements_dev.json --sarif-file-snyk-scan-requirements_dev.sarif
              deactivate
              rm -rf ~/.venv
            fi
      - name: snyk test package/lib/requirements.txt
        if: always()
        run: |
            if [ -f "requirements_dev.txt" ] && [[ $(wc -l <requirements_dev.txt) -ge 6 ]]; then
              python3.7 -m virtualenv ~/.venv -p python3 >/dev/null 2>&1
              source ~/.venv/bin/activate >/dev/null 2>&1
              (pip install -q -r package/lib/requirements.txt --use-deprecated=legacy-resolver || true) >/dev/null 2>&1
              snyk test --severity-threshold=low --print-deps --file=package/lib/requirements.txt --package-manager=pip --command=python3 --json-file-output=snyk-scan-requirements_dev.json --sarif-file-snyk-scan-requirements_dev.sarif
              deactivate
              rm -rf ~/.venv
            fi
      - name: snyk test package/lib/py2/requirements.txt
        if: always()
        run: |
            if [ -f "requirements_dev.txt" ] && [[ $(wc -l <requirements_dev.txt) -ge 6 ]]; then
              python3.7 -m virtualenv ~/.venv -p python3 >/dev/null 2>&1
              source ~/.venv/bin/activate >/dev/null 2>&1
              (pip install -q -r package/lib/py2/requirements.txt --use-deprecated=legacy-resolver || true) >/dev/null 2>&1
              snyk test --severity-threshold=low --print-deps --file=package/lib/py2/requirements.txt --package-manager=pip --command=python3 --json-file-output=snyk-scan-requirements_dev.json --sarif-file-snyk-scan-requirements_dev.sarif
              deactivate
              rm -rf ~/.venv
            fi
      - name: snyk test package/lib/py3/requirements.txt
        if: always()
        run: |
            if [ -f "requirements_dev.txt" ] && [[ $(wc -l <requirements_dev.txt) -ge 6 ]]; then
              python3.7 -m virtualenv ~/.venv -p python3 >/dev/null 2>&1
              source ~/.venv/bin/activate >/dev/null 2>&1
              (pip install -q -r package/lib/py3/requirements.txt --use-deprecated=legacy-resolver || true) >/dev/null 2>&1
              snyk test --severity-threshold=low --print-deps --file=package/lib/py3/requirements.txt --package-manager=pip --command=python3 --json-file-output=snyk-scan-requirements_dev.json --sarif-file-snyk-scan-requirements_dev.sarif
              deactivate
              rm -rf ~/.venv
            fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: my-artifact
          path: |
                snyk-scan*.json
                snyk-scan*.sarif
          if-no-files-found: ignore