name: Snyk testing

on:
  pull_request:
    branches: [develop, main, test/snyk-POC, test/snyk-POC2]
    types: [closed]

jobs:
  test:
    if: (github.ref=='test/snyk-POC2' && github.event.pull_request.user.login!='davido-splunk' && github.event.pull_request.merged==true) || (github.ref!='test/snyk-POC2' && github.event.pull_request.merged==true)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Dump GitHub context variables
        env:
          GITHUB_CONTEXT_PR: ${{ github.event.pull_request.user.login }}
          GITHUB_CONTEXT_REF: ${{ github.ref }}
          GITHUB_CONTEXT_MERGED: ${{ github.event.pull_request.merged }}
        run: |
            echo "$GITHUB_CONTEXT_PR"
            echo "$GITHUB_CONTEXT_MERGED"
            echo "$GITHUB_CONTEXT_REF"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump strategy context
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
      - uses: snyk/actions/setup@master
      - name: snyk auth - authenticate snyk use environment variables to add token
        run:  snyk auth e1086d1f-def2-4c81-bcf2-2d6002c14c05
      - run: mkdir snyk_output
      - name: snyk test package/lib/requirements.txt
        if: always()
        run: |
            if [ -f "package/lib/requirements.txt" ] && [[ $(grep -v "^\s*#" package/lib/requirements.txt | wc -l) -gt 0 ]]; then
              python3.7 -m virtualenv ~/.venv -p python3 >/dev/null 2>&1
              source ~/.venv/bin/activate >/dev/null 2>&1
              (pip install -q -r package/lib/requirements.txt --use-deprecated=legacy-resolver || true) >/dev/null 2>&1
              snyk test --severity-threshold=high --print-deps --file=package/lib/requirements.txt --package-manager=pip --command=python3 --json-file-output=snyk_output/snyk-scan-package_lib_requirements.json --sarif-file-output=snyk_output/snyk-scan-package_lib_requirements.sarif
              deactivate
              rm -rf ~/.venv
            else
              echo "File package/lib/requirements.txt is either not found or does not contain dependencies"
            fi
      - name: snyk test package/lib/py3/requirements.txt
        if: always()
        run: |
            if [ -f "package/lib/py3/requirements.txt" ] && [[ $(grep -v "^\s*#" package/lib/py3/requirements.txt | wc -l) -gt 0 ]]; then
              python3.7 -m virtualenv ~/.venv -p python3 >/dev/null 2>&1
              source ~/.venv/bin/activate >/dev/null 2>&1
              (pip install -q -r package/lib/py3/requirements.txt --use-deprecated=legacy-resolver || true) >/dev/null 2>&1
              snyk test --severity-threshold=high --print-deps --file=package/lib/py3/requirements.txt --package-manager=pip --command=python3 --json-file-output=snyk_output/snyk-scan-package_lib_py3_requirements.json --sarif-file-output=snyk_output/snyk-scan-package_lib_py3_requirements.sarif
              deactivate
              rm -rf ~/.venv
            else
              echo "File package/lib/py3/requirements.txt is either not found or does not contain dependencies"
            fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: Snyk_test_results
          path: snyk_output/*
          if-no-files-found: ignore